### ISSUE TITLE
Step Make errors with error code 100 and then 2 on server, not locally

### ISSUE THREAD

**Issue by Qwendu** [BattleRush/eth-compilerdesign-output-action#1]
.githug/workflow/makefile.yml
```
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # One can also use ubuntu-18.04 however this is getting depricated by Jan 2023
    runs-on: ubuntu-20.04 #ubuntu-latest for 22.04 (22.04 wont work with LLVM 9 however)
    environment: Token
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Cache Opam
      id: cache-ocaml
      uses: actions/cache@v3
      with:
        path: /home/runner/.opam
        key: ${{ runner.os }}-opam-4.13.1

    - name: Cache LLVM
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: ./llvm
        key: llvm-9

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "9.0"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}

    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v1.1.11
      with:
        ocaml-version: 4.13.1

    # Change to opam environment after 4.13.1 switch and install needed packages
    - run: eval $(opam env)
    - run: opam install ocamlbuild
    - run: opam install menhir
    - run: opam install num

    - name: Run make
      id: maketest
      run: |
        eval $(opam env)
        make > make.out

    - name: Create GitHub Action markdown
      id: outputparser
      uses: BattleRush/eth-compilerdesign-output-action@main
      with:
          make-output: make.out
          token: ${{secrets.PAT}}
          leaderboard: true
          teamname: 'Not Compiler Design'

    - name: Get the output markdown
      run: echo "${{ steps.outputparser.outputs.markdown }}" >> $GITHUB_STEP_SUMMARY
      ```
      
      Makefile:
      ```
      SUBDIRS := $(wildcard */.)
SUBDIRS := $(filter-out _build/.,$(SUBDIRS))
SUBDIRS := $(filter-out llvm/.,$(SUBDIRS))

MAKE := make test

all: $(SUBDIRS)
$(SUBDIRS):
	$(MAKE) -C $@;\

.PHONY: all $(SUBDIRS)
```

**Comment by Qwendu** [comment]
Output by workflow
```
Run eval $(opam env)
  eval $(opam env)
  make > make.out
  shell: /usr/bin/bash -e {0}
  env:
    LLVM_PATH: /home/runner/work/NotCompilerDesign/NotCompilerDesign/llvm
    LD_LIBRARY_PATH: /home/runner/work/NotCompilerDesign/NotCompilerDesign/llvm/lib:
    DYLD_LIBRARY_PATH: /home/runner/work/NotCompilerDesign/NotCompilerDesign/llvm/lib:
    OPAMJOBS: 4
    OPAMYES: 1
make[1]: *** [Makefile:8: main.native] Error 100
make: *** [Makefile:9: hw1/.] Error 2
Error: Process completed with exit code 2.
```

**Comment by BattleRush** [comment]
Closed as fixed with new repository

**Comment by Starbix** [comment]
~I still get that error. It works fine locally~ Works now for some reason. Thanks for the action!
